server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
            - id: resource-service
              uri: http://localhost:8082
              predicates:
                - Path=/resource/**

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

    disable-swagger-default-url: true

    urls:
      - name: Auth service
        url: /auth/v3/api-docs
      - name: Resource service
        url: /resource/v3/api-docs
