server:
  port: ${RESOURCE_PORT:8082}
  servlet:
    context-path: /resource

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:

  application:
    name: resource

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/auth

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:laserworks}
    username: ${POSTGRES_USER:laserworks}
    password: ${POSTGRES_PASSWORD:laserworks}

  jpa:
    hibernate:
      ddl-auto: validate

minio:
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  accessKey: ${MINIO_ROOT_USER:minioadmin}
  secretKey: ${MINIO_ROOT_PASSWORD:minioadmin}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    oauth:
      client-id: ${AUTH_SWAGGER_CLIENT_ID:swagger}
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/resource/swagger-ui/oauth2-redirect.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

app:
  feign:
    auth-url: http://${AUTH_HOST:localhost}:${AUTH_PORT:8081}/auth
  swagger:
    server-url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/resource
  security:
    oauth2:
      authorization-url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/auth/oauth2/authorize
      token-url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/auth/oauth2/token